import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Compass, Stack, GlobeHemisphereWest, ChartLineUp, ArrowUpRight, CheckCircle, Clock, Paperclip, SidebarSimple } from '@phosphor-icons/react';
import { DesktopRoot, DesktopShell, NavigationRail, AvatarMenu, Button, IconButton, Input, Textarea, Select, Tabs, PageBar, WorkbenchPage, InternalScrollArea, Dialog, EmptyState, SettingsNavigation, SettingsPage, SettingsSection, SettingRow, Switch, Checkbox, useDesktopTheme, House, ChatCircle, Gear, Plus, ArrowUp, MagnifyingGlass } from '../../src';
import '../../src/styles.css';
import './demo.css';
import { projects as initialProjects, conversations, type Project } from './data';

const navigation = [{ id: 'projects', label: 'Projects', icon: House }, { id: 'inbox', label: 'Inbox', icon: ChatCircle, unread: true }, { id: 'settings', label: 'Settings', icon: Gear }];
const categories = [{ id: 'appearance', label: 'Appearance', keywords: ['theme', 'display'] }, { id: 'preferences', label: 'Preferences', keywords: ['notifications', 'workspace'] }];
const symbols = { compass: Compass, layers: Stack, globe: GlobeHemisphereWest, chart: ChartLineUp };
const themeOptions = [{ value: 'system', label: 'System' }, { value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }];

function Demo() {
  const { theme, setTheme } = useDesktopTheme();
  const [page, setPage] = useState('projects');
  const [sidebar, setSidebar] = useState(true);
  const [tab, setTab] = useState('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('due');
  const [projects, setProjects] = useState(initialProjects);
  const [selected, setSelected] = useState<Project | null>(null);
  const [category, setCategory] = useState('appearance');
  const [room, setRoom] = useState('launch');
  const [messages, setMessages] = useState(() => Object.fromEntries(conversations.map(item => [item.id, item.messages])));
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [create, setCreate] = useState(false);
  const [discard, setDiscard] = useState(false);
  const [name, setName] = useState('');
  const [summary, setSummary] = useState('');
  const [formError, setFormError] = useState('');
  const [notice, setNotice] = useState('');
  const [notifications, setNotifications] = useState(true);
  const [workspaceName, setWorkspaceName] = useState('Northstar');
  const [checked, setChecked] = useState<string[]>([]);
  const scroll = useRef<HTMLDivElement>(null);
  const searchInput = useRef<HTMLInputElement>(null);
  const visible = projects.filter(item => `${item.name} ${item.owner} ${item.summary} ${item.tasks.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (tab === 'all' || (tab === 'active' ? item.state === 'In progress' : item.state === 'In review'))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : (Date.parse(`${a.due}, 2026`) || Infinity) - (Date.parse(`${b.due}, 2026`) || Infinity));
  const conversation = conversations.find(item => item.id === room)!;
  useEffect(() => { scroll.current?.scrollTo({ top: scroll.current.scrollHeight }); }, [room, messages]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => {
    const preventLoss = (event: BeforeUnloadEvent) => { if (name || summary || Object.values(drafts).some(Boolean)) event.preventDefault(); };
    window.addEventListener('beforeunload', preventLoss); return () => window.removeEventListener('beforeunload', preventLoss);
  }, [name, summary, drafts]);
  const closeCreate = () => { if (name || summary) setDiscard(true); else { setCreate(false); setFormError(''); } };
  const clearCreate = () => { setCreate(false); setDiscard(false); setName(''); setSummary(''); setFormError(''); };
  const createProject = () => {
    if (!name.trim()) { setFormError('Give this project a name before creating it.'); return; }
    if (projects.some(item => item.name.toLowerCase() === name.trim().toLowerCase())) { setFormError('A project with this name already exists. Choose another name.'); return; }
    setProjects(old => [...old, { id: `local-${crypto.randomUUID()}`, name: name.trim(), summary: summary.trim() || 'Add a few notes when the plan takes shape.', state: 'Planned', completed: 0, total: 3, due: 'Not scheduled', owner: 'Alex Taylor', initials: 'AT', icon: 'compass', tasks: ['Write the project brief', 'Agree on the first milestone', 'Invite the project team'] }]);
    setQuery(''); setTab('all'); clearCreate(); setNotice('Project created in this demo session.');
  };
  const send = () => {
    const text = (drafts[room] || '').trim(); if (!text) return;
    setMessages(old => ({ ...old, [room]: [...old[room], { name: 'Alex Taylor', initials: 'AT', time: 'Just now', text, own: true }] }));
    setDrafts(old => ({ ...old, [room]: '' }));
  };
  const side = page === 'settings' ? <SettingsNavigation categories={categories} selected={category} onSelect={setCategory}/> : page === 'inbox' ? <div className="demo-inbox-sidebar" data-phd-feature="demo.inbox" data-phd-surface="demo.conversations"><div className="demo-side-heading">Team conversations<span>3</span></div><InternalScrollArea>{conversations.map(item => <Button key={item.id} className="demo-room" actionId="demo.conversation.select" aria-current={room === item.id ? 'page' : undefined} onClick={() => setRoom(item.id)}><span className="demo-room-title">{item.title}<small>{item.time}</small></span><span className="demo-room-preview">{item.preview}</span></Button>)}</InternalScrollArea><p className="demo-side-note">A little context goes a long way.</p></div> : undefined;
  return <div className="demo-app" data-phd-feature="demo.workspace" data-phd-surface="demo.app">
    <header className="demo-topbar"><div className="demo-wordmark"><Compass size={22} weight="fill"/><span>{workspaceName}</span><span className="demo-top-separator">/</span><span className="demo-muted">Product workspace</span></div><div className="demo-top-actions"><span className="demo-demo-label">Interactive demo</span><Select aria-label="Theme" actionId="demo.theme.change" value={theme} options={themeOptions} onValueChange={value => setTheme(value as typeof theme)}/><a className="demo-source" data-phd-action="demo.source.open" href="https://github.com/liuminxin45/ChatGPT-Desktop-UI" target="_blank" rel="noreferrer">View source<ArrowUpRight size={14}/></a></div></header>
    <DesktopShell navigation={<NavigationRail items={navigation} selected={page} onSelect={setPage} footer={<AvatarMenu name="Alex Taylor" status="Northstar · Product design" onSettings={() => setPage('settings')}/>}/>} sidebar={side} sidebarVisible={page === 'inbox' ? sidebar : true}>
      <section className="demo-panel" hidden={page !== 'projects'} data-phd-feature="demo.projects" data-phd-surface="demo.projects.list"><WorkbenchPage>
        <PageBar className="phd-workbench__bar" navigation={<Tabs actionId="demo.projects.filter" value={tab} onValueChange={setTab} items={[{ value: 'all', label: 'All projects' }, { value: 'active', label: 'In progress' }, { value: 'review', label: 'In review' }]}/>} actions={<Button actionId="demo.project.create.open" onClick={() => setCreate(true)}><Plus size={16}/>New project</Button>}/>
        <InternalScrollArea className="demo-project-scroll"><div className="demo-intro"><div><p className="demo-eyebrow">Friday, October 9</p><h1>Good work starts with a clear view.</h1><p className="demo-muted">A few thoughtful changes. A better everyday experience.</p></div><div className="demo-team"><div className="demo-avatar-stack">{['MC','OR','AM','AT'].map(initials => <span className="demo-avatar" key={initials}>{initials}</span>)}</div><span className="demo-muted">Your product team</span></div></div>
          <div className="demo-section-heading"><div>Projects<span className="demo-count">{visible.length}</span></div><div className="demo-filters"><div className="demo-search"><MagnifyingGlass size={16}/><Input ref={searchInput} aria-label="Search projects" data-phd-action="demo.projects.search" placeholder="Search projects" value={query} onChange={event => setQuery(event.target.value)}/></div><Select actionId="demo.projects.sort" aria-label="Sort projects" value={sort} onValueChange={setSort} options={[{ value: 'due', label: 'Due date' }, { value: 'name', label: 'Name' }]}/></div></div>
          {visible.length ? <div className="demo-projects">{visible.map(project => { const Symbol = symbols[project.icon]; return <article key={project.id} className="demo-project"><div className="demo-card-top"><span className="demo-project-symbol"><Symbol size={24}/></span><span className={`demo-status demo-status--${project.state.replaceAll(' ', '-').toLowerCase()}`}>{project.state}</span></div><h2><Button actionId="demo.project.open" className="demo-project-link" onClick={() => setSelected(project)}>{project.name}<ArrowUpRight size={16}/></Button></h2><p className="demo-project-summary">{project.summary}</p><div className="demo-progress-label"><span>{project.completed} of {project.total} tasks</span><span>{Math.round(project.completed / project.total * 100)}%</span></div><div className="demo-progress" role="progressbar" aria-label={`${project.name} progress`} aria-valuenow={project.completed} aria-valuemin={0} aria-valuemax={project.total}><span style={{ width: `${project.completed / project.total * 100}%` }}/></div><div className="demo-card-footer"><span><span className="demo-avatar demo-avatar--small">{project.initials}</span>{project.owner}</span><span><Clock size={14}/>{project.due}</span></div></article>; })}</div> : <EmptyState title="No matching projects" description="Try a project name, a topic or a teammate." action={<Button actionId="demo.projects.search.clear" onClick={() => { setQuery(''); setTab('all'); }}>Clear filters</Button>}/>}
          <div className="demo-lower"><section><div className="demo-section-heading">Next up<span className="demo-muted">Your focus for today</span></div>{[{ id: 'review', title: 'Review the invite flow', project: 'A better first five minutes', time: 'Today · 2:00 pm' }, { id: 'handoff', title: 'Finish the component handoff', project: 'One language for every screen', time: 'Today · 4:30 pm' }, { id: 'ranking', title: 'Check the search ranking results', project: 'Find the work, not the folder', time: 'Monday' }].map(task => <label className="demo-task" key={task.id}><Checkbox aria-label={`Complete ${task.title}`} data-phd-action="demo.task.complete" checked={checked.includes(task.id)} onChange={() => setChecked(old => old.includes(task.id) ? old.filter(id => id !== task.id) : [...old, task.id])}/><span className={checked.includes(task.id) ? 'demo-completed' : ''}>{task.title}<small>{task.project}</small></span><span className="demo-muted">{task.time}</span></label>)}</section><section className="demo-note"><div className="demo-section-heading"><span>From the team</span><ChatCircle size={18}/></div><p>“The best part of the new flow is what we took out. It finally feels like one conversation, not a checklist.”</p><div className="demo-note-person"><span className="demo-avatar">MC</span><span>Maya Chen<small>After yesterday’s onboarding review</small></span></div><Button size="sm" actionId="demo.discussion.open" onClick={() => { setRoom('launch'); setPage('inbox'); }}>Join the discussion<ArrowUpRight size={14}/></Button></section></div>
          <footer className="demo-footnote"><span>Built with ChatGPT Desktop UI Kit</span><span>Fictional workspace · Changes last until you reload</span></footer>
        </InternalScrollArea>
      </WorkbenchPage></section>
      <section className="demo-panel demo-chat" hidden={page !== 'inbox'} data-phd-feature="demo.inbox" data-phd-surface="demo.conversation"><PageBar className="phd-workbench__bar" navigation={<div className="demo-chat-title"><IconButton actionId="demo.sidebar.toggle" aria-label="Toggle conversations" onClick={() => setSidebar(old => !old)}><SidebarSimple size={18}/></IconButton><span>{conversation.title}</span><span className="demo-muted">Product team</span></div>} actions={<Button size="sm" actionId="demo.discussion.project.open" onClick={() => setSelected(projects[room === 'design' ? 1 : room === 'search' ? 2 : 0])}>View project<ArrowUpRight size={14}/></Button>}/>
        <InternalScrollArea ref={scroll} className="demo-messages"><div className="demo-reading"><div className="demo-chat-date">Friday, October 9</div>{messages[room].map((message, index) => <article className={`demo-message${message.own ? ' demo-message--own' : ''}`} key={index}><span className="demo-avatar">{message.initials}</span><div><div className="demo-message-meta">{message.name}<small>{message.time}</small></div><p>{message.text}</p></div></article>)}{room === 'launch' ? <div className="demo-discussion-context"><CheckCircle size={16}/><span>Decision: keep profile setup out of the invite flow.</span></div> : null}</div></InternalScrollArea>
        <form className="phd-composer demo-composer" onSubmit={event => { event.preventDefault(); send(); }}><Textarea aria-label="Message" placeholder={`Message ${conversation.title.toLowerCase()}…`} value={drafts[room] || ''} data-phd-action="demo.message.edit" onChange={event => setDrafts(old => ({ ...old, [room]: event.target.value }))}/><div><div className="demo-composer-hint"><Paperclip size={16}/><span>Enter to send · Shift + Enter for a new line</span></div><Button type="submit" className="phd-send-control" aria-label="Send message" actionId="demo.message.send" disabled={!(drafts[room] || '').trim()}><ArrowUp size={18}/></Button></div></form><p className="demo-chat-local">Messages stay in this browser session.</p>
      </section>
      <section className="demo-panel" hidden={page !== 'settings'} data-phd-feature="demo.settings" data-phd-surface="demo.settings.form"><SettingsPage title={category === 'appearance' ? 'Appearance' : 'Preferences'}><div hidden={category !== 'appearance'}><SettingsSection title="Make yourself at home"><SettingRow label="Theme" description="Follow your system or choose a look that feels right."><Select aria-label="Settings theme" actionId="demo.settings.theme" value={theme} options={themeOptions} onValueChange={value => setTheme(value as typeof theme)}/></SettingRow><SettingRow label="Interface language"><Select aria-label="Interface language" actionId="demo.settings.language" value="en" options={[{ value: 'en', label: 'English' }]}/></SettingRow></SettingsSection><SettingsSection title="About this demo"><SettingRow label="React components, in your browser" description="The same controls and theme tokens used by desktop hosts. No desktop runtime required.">{null}</SettingRow><SettingRow label="Sample workspace" description="People, discussions and project details are fictional. Edits stay in memory; only your theme preference is saved.">{null}</SettingRow></SettingsSection></div><div hidden={category !== 'preferences'}><SettingsSection title="Workspace"><SettingRow label="Workspace name"><Input aria-label="Workspace name" data-phd-action="demo.settings.workspace" maxLength={32} value={workspaceName} onChange={event => setWorkspaceName(event.target.value)}/></SettingRow><SettingRow label="In-app reminders" description="Show a reminder preview in this demo."><Switch aria-label="In-app reminders" actionId="demo.settings.reminders" checked={notifications} onClick={() => { setNotifications(old => !old); setNotice(notifications ? 'Reminder preview is off.' : 'Reminder preview: the invite flow review starts at 2 pm.'); }}/></SettingRow></SettingsSection><p className="demo-muted">Your drafts stay put when you change themes or switch pages.</p></div></SettingsPage></section>
    </DesktopShell>
    <Dialog open={create} title={discard ? 'Discard this project?' : 'New project'} actionId="demo.project.dialog" onClose={() => discard ? setDiscard(false) : closeCreate()} footer={discard ? <><Button actionId="demo.project.draft.keep" onClick={() => setDiscard(false)}>Keep editing</Button><Button variant="danger" actionId="demo.project.draft.discard" onClick={clearCreate}>Discard</Button></> : <><Button actionId="demo.project.create.cancel" onClick={closeCreate}>Cancel</Button><Button variant="primary" confirmOnEnter actionId="demo.project.create.confirm" onClick={createProject}>Create project</Button></>}>{discard ? <p>Your unsaved project details will be lost.</p> : <div className="demo-form"><label>Project name<Input autoFocus maxLength={80} value={name} onChange={event => { setName(event.target.value); setFormError(''); }} placeholder="What are you working on?"/></label><label>Brief<Textarea maxLength={240} value={summary} onChange={event => setSummary(event.target.value)} placeholder="A sentence or two about the outcome."/></label>{formError ? <p role="alert">{formError}</p> : null}<p className="demo-muted">Created projects are available until you reload this demo.</p></div>}</Dialog>
    <Dialog open={!!selected} title={selected?.name} actionId="demo.project.details" onClose={() => setSelected(null)} footer={<Button actionId="demo.project.details.close" onClick={() => setSelected(null)}>Done</Button>}>{selected ? <div className="demo-details"><p className="demo-muted">{selected.summary}</p><div className="demo-details-meta"><span className="demo-avatar">{selected.initials}</span><span>{selected.owner}</span><span className="demo-status">{selected.state}</span></div><h2>Next milestones</h2>{selected.tasks.map(task => <p className="demo-milestone" key={task}><CheckCircle size={17}/>{task}</p>)}<div className="demo-details-bottom"><Clock size={15}/>Due {selected.due}</div></div> : null}</Dialog>
    {notice ? <div className="demo-toast" role="status"><CheckCircle size={18}/>{notice}</div> : null}
  </div>;
}
createRoot(document.getElementById('root')!).render(<DesktopRoot storageKey="desktop-kit.demo.theme"><Demo/></DesktopRoot>);
