import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Compass, Stack, GlobeHemisphereWest, ChartLineUp, GithubLogo, Bell, Sliders, ArrowUpRight, CheckCircle, Clock, Paperclip, SidebarSimple } from '@phosphor-icons/react';
import { DesktopRoot, DesktopShell, TitleBar, Tooltip, NavigationRail, AvatarMenu, Button, IconButton, Input, Textarea, Select, Tabs, PageBar, WorkbenchPage, InternalScrollArea, Dialog, EmptyState, SettingsNavigation, SettingsPage, SettingsSection, SettingRow, Switch, Checkbox, useDesktopTheme, House, ChatCircle, Gear, Plus, ArrowUp, MagnifyingGlass } from '../../src';
import '../../src/styles.css';
import './demo.css';
import { ActivityChart } from './ActivityChart';
import { useNavigation } from './useNavigation';
import { projects as initialProjects, conversations, type Project } from './data';

const navigationItems = [{ id: 'projects', label: 'Projects', icon: House }, { id: 'inbox', label: 'Inbox', icon: ChatCircle, unread: true }, { id: 'activity', label: 'Activity', icon: ChartLineUp }, { id: 'settings', label: 'Settings', icon: Gear }];
const categories = [{ id: 'appearance', label: 'Appearance', group: 'Personal', icon: Sliders, keywords: ['theme', 'display'] }, { id: 'notifications', label: 'Notifications', group: 'Personal', icon: Bell, keywords: ['alerts'] }, { id: 'preferences', label: 'Preferences', group: 'Workspace', icon: Gear, keywords: ['name', 'navigation'] }];
const symbols = { compass: Compass, layers: Stack, globe: GlobeHemisphereWest, chart: ChartLineUp };
const themeOptions = [{ value: 'system', label: 'System' }, { value: 'light', label: 'Light' }, { value: 'dark', label: 'Dark' }];

function Demo() {
  const { theme, setTheme } = useDesktopTheme();
  const navigation = useNavigation();
  const { page, category, room } = navigation.route;
  const setPage = (page: string) => navigation.navigate({ page });
  const setCategory = (category: string) => navigation.navigate({ category });
  const setRoom = (room: string) => navigation.navigate({ room });
  const [pinned, setPinned] = useState(['projects', 'inbox', 'activity', 'settings']);
  const [help, setHelp] = useState<'about' | 'shortcuts' | null>(null);
  const [sidebar, setSidebar] = useState(true);
  const [tab, setTab] = useState('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('due');
  const [projects, setProjects] = useState(initialProjects);
  const [selected, setSelected] = useState<Project | null>(null);
  const [messages, setMessages] = useState(() => Object.fromEntries(conversations.map(item => [item.id, item.messages])));
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [create, setCreate] = useState(false);
  const [discard, setDiscard] = useState(false);
  const [name, setName] = useState('');
  const [summary, setSummary] = useState('');
  const [formError, setFormError] = useState('');
  const [notice, setNotice] = useState('');
  const [notifications, setNotifications] = useState(true);
  const [workspaceName, setWorkspaceName] = useState('Northstar');
  const [taskHistory, setTaskHistory] = useState<{ entries: string[][]; index: number }>({ entries: [[]], index: 0 });
  const checked = taskHistory.entries[taskHistory.index];
  const toggleTask = (id: string) => setTaskHistory(old => { const before = old.entries[old.index]; return { entries: [...old.entries.slice(0, old.index + 1), before.includes(id) ? before.filter(item => item !== id) : [...before, id]], index: old.index + 1 }; });
  const moveTask = (offset: number) => setTaskHistory(old => ({ ...old, index: Math.max(0, Math.min(old.entries.length - 1, old.index + offset)) }));
  const scroll = useRef<HTMLDivElement>(null);
  const searchInput = useRef<HTMLInputElement>(null);
  const visible = projects.filter(item => `${item.name} ${item.owner} ${item.summary} ${item.tasks.join(' ')}`.toLowerCase().includes(query.toLowerCase()) && (tab === 'all' || (tab === 'active' ? item.state === 'In progress' : item.state === 'In review'))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : (Date.parse(`${a.due}, 2026`) || Infinity) - (Date.parse(`${b.due}, 2026`) || Infinity));
  const conversation = conversations.find(item => item.id === room)!;
  useEffect(() => { scroll.current?.scrollTo({ top: scroll.current.scrollHeight }); }, [room, messages]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 4500); return () => clearTimeout(timer); }, [notice]);
  useEffect(() => {
    const preventLoss = (event: BeforeUnloadEvent) => { if (name || summary || Object.values(drafts).some(Boolean)) event.preventDefault(); };
    window.addEventListener('beforeunload', preventLoss); return () => window.removeEventListener('beforeunload', preventLoss);
  }, [name, summary, drafts]);
  const closeCreate = () => { if (name || summary) setDiscard(true); else { setCreate(false); setFormError(''); } };
  const clearCreate = () => { setCreate(false); setDiscard(false); setName(''); setSummary(''); setFormError(''); };
  const createProject = () => {
    if (!name.trim()) { setFormError('Give this project a name before creating it.'); return; }
    if (projects.some(item => item.name.toLowerCase() === name.trim().toLowerCase())) { setFormError('A project with this name already exists. Choose another name.'); return; }
    setProjects(old => [...old, { id: `local-${crypto.randomUUID()}`, name: name.trim(), summary: summary.trim() || 'Add a few notes when the plan takes shape.', state: 'Planned', completed: 0, total: 3, due: 'Not scheduled', owner: 'Alex Taylor', initials: 'AT', icon: 'compass', tasks: ['Write the project brief', 'Agree on the first milestone', 'Invite the project team'] }]);
    setQuery(''); setTab('all'); clearCreate(); setNotice('Project created in this demo session.');
  };
  const send = () => {
    const text = (drafts[room] || '').trim(); if (!text) return;
    setMessages(old => ({ ...old, [room]: [...old[room], { name: 'Alex Taylor', initials: 'AT', time: 'Just now', text, own: true }] }));
    setDrafts(old => ({ ...old, [room]: '' }));
  };
  const side = <div className="demo-side-panels"><div hidden={page !== 'settings'}><SettingsNavigation categories={categories} selected={category} onSelect={setCategory}/></div><div className="demo-inbox-sidebar" hidden={page !== 'inbox'} data-phd-feature="demo.inbox" data-phd-surface="demo.conversations"><div className="demo-side-heading">Team conversations</div><InternalScrollArea>{conversations.map(item => <Button key={item.id} className="demo-room" actionId="demo.conversation.select" aria-current={room === item.id ? 'page' : undefined} onClick={() => setRoom(item.id)}><span className="demo-room-title">{item.title}<small>{item.time}</small></span><span className="demo-room-preview">{item.preview}</span></Button>)}</InternalScrollArea></div></div>;
  const menus = [
    { id:'file', label:'File', actions:[{ id:'demo.project.create.open', label:'New project', onSelect:() => setCreate(true) }, { id:'demo.projects.open', label:'Open projects', onSelect:() => setPage('projects') }, { id:'demo.settings.open', label:'Settings', onSelect:() => setPage('settings') }] },
    { id:'edit', label:'Edit', actions:[{ id:'demo.task.undo', label:'Undo task change', disabled:taskHistory.index === 0, onSelect:() => moveTask(-1) }, { id:'demo.task.redo', label:'Redo task change', disabled:taskHistory.index === taskHistory.entries.length - 1, onSelect:() => moveTask(1) }, { id:'demo.projects.find', label:'Find projects', onSelect:() => { setPage('projects'); setTimeout(() => searchInput.current?.focus(), 0); } }, { id:'demo.projects.search.clear', label:'Clear search', disabled:!query, onSelect:() => setQuery('') }] },
    { id:'view', label:'View', actions:[{ id:'demo.sidebar.toggle', label:sidebar ? 'Hide sidebar' : 'Show sidebar', onSelect:() => setSidebar(old => !old) }, { id:'demo.activity.open', label:'Activity', onSelect:() => setPage('activity') }, { id:'demo.theme.toggle', label:theme === 'dark' ? 'Use light theme' : 'Use dark theme', onSelect:() => setTheme(theme === 'dark' ? 'light' : 'dark') }] },
    { id:'help', label:'Help', actions:[{ id:'demo.shortcuts.open', label:'Keyboard shortcuts', onSelect:() => setHelp('shortcuts') }, { id:'demo.about.open', label:'About Northstar', onSelect:() => setHelp('about') }] },
  ];
  return <div className="demo-app" data-phd-feature="demo.workspace" data-phd-surface="demo.app">
    <DesktopShell titlebar={<TitleBar menus={menus} canBack={navigation.canBack} canForward={navigation.canForward} onBack={navigation.back} onForward={navigation.forward} canToggleSidebar onToggleSidebar={() => setSidebar(old => !old)} labels={{ back:'Back', forward:'Forward', sidebar:'Toggle sidebar' }} trailing={<div className="demo-top-actions"><span className="demo-wordmark"><Compass size={18} weight="fill"/><span>{workspaceName}</span></span><Select aria-label="Theme" actionId="demo.theme.change" value={theme} options={themeOptions} onValueChange={value => setTheme(value as typeof theme)}/><Tooltip label="View source" side="bottom"><a className="phd-icon-control" data-phd-action="demo.source.open" aria-label="View source" href="https://github.com/liuminxin45/ChatGPT-Desktop-UI" target="_blank" rel="noreferrer"><GithubLogo size={20} weight="fill" aria-hidden="true"/></a></Tooltip></div>}/>}
      navigation={<NavigationRail items={navigationItems} selected={page} onSelect={setPage} pinnedIds={pinned} onPinnedChange={setPinned} footer={<AvatarMenu name="Alex Taylor" status="Northstar · Product design" onSettings={() => setPage('settings')}/>}/>} navigationVisible={sidebar} sidebar={side} sidebarVisible={sidebar && ['inbox','settings'].includes(page)}>
      <section className="demo-panel" hidden={page !== 'projects'} data-phd-feature="demo.projects" data-phd-surface="demo.projects.list"><WorkbenchPage>
        <PageBar className="phd-workbench__bar" navigation={<Tabs actionId="demo.projects.filter" value={tab} onValueChange={setTab} items={[{ value: 'all', label: 'All projects' }, { value: 'active', label: 'In progress' }, { value: 'review', label: 'In review' }]}/>} actions={<Button actionId="demo.project.create.open" onClick={() => setCreate(true)}><Plus size={16}/>New project</Button>}/>
        <InternalScrollArea className="demo-project-scroll"><div className="demo-intro"><span className="demo-eyebrow">Friday, October 9</span><div className="demo-avatar-stack">{['MC','OR','AM','AT'].map(initials => <span className="demo-avatar" key={initials}>{initials}</span>)}</div></div>
          <div className="demo-section-heading"><div>Projects<span className="demo-count">{visible.length}</span></div><div className="demo-filters"><div className="demo-search"><MagnifyingGlass size={16}/><Input ref={searchInput} aria-label="Search projects" data-phd-action="demo.projects.search" placeholder="Search projects" value={query} onChange={event => setQuery(event.target.value)}/></div><Select actionId="demo.projects.sort" aria-label="Sort projects" value={sort} onValueChange={setSort} options={[{ value: 'due', label: 'Due date' }, { value: 'name', label: 'Name' }]}/></div></div>
          {visible.length ? <div className="demo-projects">{visible.map(project => { const Symbol = symbols[project.icon]; return <article key={project.id} className="demo-project"><div className="demo-card-top"><span className="demo-project-symbol"><Symbol size={24}/></span><span className={`demo-status demo-status--${project.state.replaceAll(' ', '-').toLowerCase()}`}>{project.state}</span></div><h2><Button actionId="demo.project.open" className="demo-project-link" onClick={() => setSelected(project)}>{project.name}<ArrowUpRight size={16}/></Button></h2><p className="demo-project-summary">{project.summary}</p><div className="demo-progress-label"><span>{project.completed} of {project.total} tasks</span><span>{Math.round(project.completed / project.total * 100)}%</span></div><div className="demo-progress" role="progressbar" aria-label={`${project.name} progress`} aria-valuenow={project.completed} aria-valuemin={0} aria-valuemax={project.total}><span style={{ width: `${project.completed / project.total * 100}%` }}/></div><div className="demo-card-footer"><span><span className="demo-avatar demo-avatar--small">{project.initials}</span>{project.owner}</span><span><Clock size={14}/>{project.due}</span></div></article>; })}</div> : <EmptyState title="No matching projects" description="Try a project name, a topic or a teammate." action={<Button actionId="demo.projects.search.clear" onClick={() => { setQuery(''); setTab('all'); }}>Clear filters</Button>}/>}
          <div className="demo-lower"><section><div className="demo-section-heading">Next up</div>{[{ id: 'review', title: 'Review the invite flow', project: 'A better first five minutes', time: 'Today · 2:00 pm' }, { id: 'handoff', title: 'Finish the component handoff', project: 'One language for every screen', time: 'Today · 4:30 pm' }, { id: 'ranking', title: 'Check the search ranking results', project: 'Find the work, not the folder', time: 'Monday' }].map(task => <label className="demo-task" key={task.id}><Checkbox aria-label={`Complete ${task.title}`} data-phd-action="demo.task.complete" checked={checked.includes(task.id)} onChange={() => toggleTask(task.id)}/><span className={checked.includes(task.id) ? 'demo-completed' : ''}>{task.title}<small>{task.project}</small></span><span className="demo-muted">{task.time}</span></label>)}</section><ActivityChart compact/></div>

        </InternalScrollArea>
      </WorkbenchPage></section>
      <section className="demo-panel demo-chat" hidden={page !== 'inbox'} data-phd-feature="demo.inbox" data-phd-surface="demo.conversation"><PageBar className="phd-workbench__bar" navigation={<div className="demo-chat-title"><span>{conversation.title}</span></div>} actions={<Button size="sm" actionId="demo.discussion.project.open" onClick={() => setSelected(projects[room === 'design' ? 1 : room === 'search' ? 2 : 0])}>View project<ArrowUpRight size={14}/></Button>}/>
        <InternalScrollArea ref={scroll} className="demo-messages"><div className="demo-reading"><div className="demo-chat-date">Friday, October 9</div>{messages[room].map((message, index) => <article className={`demo-message${message.own ? ' demo-message--own' : ''}`} key={index}><span className="demo-avatar">{message.initials}</span><div><div className="demo-message-meta">{message.name}<small>{message.time}</small></div><p>{message.text}</p></div></article>)}{room === 'launch' ? <div className="demo-discussion-context"><CheckCircle size={16}/><span>Decision: keep profile setup out of the invite flow.</span></div> : null}</div></InternalScrollArea>
        <form className="phd-composer demo-composer" onSubmit={event => { event.preventDefault(); send(); }}><Textarea aria-label="Message" placeholder={`Message ${conversation.title.toLowerCase()}…`} value={drafts[room] || ''} data-phd-action="demo.message.edit" onChange={event => setDrafts(old => ({ ...old, [room]: event.target.value }))}/><div><div className="demo-composer-hint"><Paperclip size={16}/><span>Enter to send · Shift + Enter for a new line</span></div><Button type="submit" className="phd-send-control" aria-label="Send message" actionId="demo.message.send" disabled={!(drafts[room] || '').trim()}><ArrowUp size={18}/></Button></div></form>
      </section>
      <section className="demo-panel" hidden={page !== 'activity'} data-phd-feature="demo.activity" data-phd-surface="demo.activity.page"><WorkbenchPage><PageBar className="phd-workbench__bar" navigation={<span>Activity</span>} actions={<Button actionId="demo.activity.projects" onClick={() => setPage('projects')}>View projects<ArrowUpRight size={14}/></Button>}/><InternalScrollArea className="demo-activity-scroll"><div className="demo-activity-summary"><section><h2>Completed this week</h2><p>25<span>+3 from last week</span></p></section><section><h2>Opened this week</h2><p>29<span>+5 from last week</span></p></section><section><h2>Median cycle time</h2><p>3.2<span>days</span></p></section></div><ActivityChart/><div className="demo-activity-bottom"><h2>Recent decisions</h2><Button actionId="demo.discussion.open" onClick={() => navigation.navigate({ page:'inbox', room:'launch' })}>Keep profile setup out of the invite flow<ArrowUpRight size={14}/></Button><Button actionId="demo.design.open" onClick={() => navigation.navigate({ page:'inbox', room:'design' })}>Include focus states in the component handoff<ArrowUpRight size={14}/></Button></div></InternalScrollArea></WorkbenchPage></section>
      <section className="demo-panel" hidden={page !== 'settings'} data-phd-feature="demo.settings" data-phd-surface="demo.settings.form"><SettingsPage title={categories.find(item => item.id === category)?.label || 'Appearance'}><div hidden={category !== 'appearance'}><SettingsSection title="Display"><SettingRow label="Theme"><Select aria-label="Settings theme" actionId="demo.settings.theme" value={theme} options={themeOptions} onValueChange={value => setTheme(value as typeof theme)}/></SettingRow><SettingRow label="Interface language"><Select aria-label="Interface language" actionId="demo.settings.language" value="en" options={[{ value:'en', label:'English' }]}/></SettingRow></SettingsSection><SettingsSection title="Navigation"><SettingRow label="Sidebar"><Switch aria-label="Show sidebar" actionId="demo.settings.sidebar" checked={sidebar} onClick={() => setSidebar(old => !old)}/></SettingRow><SettingRow label="Pinned destinations"><Button size="sm" actionId="demo.navigation.reset" onClick={() => setPinned(['projects','inbox','activity','settings'])}>Reset pins</Button></SettingRow></SettingsSection></div><div hidden={category !== 'notifications'}><SettingsSection title="Reminders"><SettingRow label="In-app reminders" description="Notify me before scheduled reviews."><Switch aria-label="In-app reminders" actionId="demo.settings.reminders" checked={notifications} onClick={() => { setNotifications(old => !old); setNotice(notifications ? 'Reminders off.' : 'Invite flow review · Today at 2 pm'); }}/></SettingRow></SettingsSection></div><div hidden={category !== 'preferences'}><SettingsSection title="General"><SettingRow label="Workspace name"><Input aria-label="Workspace name" data-phd-action="demo.settings.workspace" maxLength={32} value={workspaceName} onChange={event => setWorkspaceName(event.target.value)}/></SettingRow></SettingsSection></div></SettingsPage></section>
    </DesktopShell>
    <Dialog open={create} title={discard ? 'Discard this project?' : 'New project'} actionId="demo.project.dialog" onClose={() => discard ? setDiscard(false) : closeCreate()} footer={discard ? <><Button actionId="demo.project.draft.keep" onClick={() => setDiscard(false)}>Keep editing</Button><Button variant="danger" actionId="demo.project.draft.discard" onClick={clearCreate}>Discard</Button></> : <><Button actionId="demo.project.create.cancel" onClick={closeCreate}>Cancel</Button><Button variant="primary" confirmOnEnter actionId="demo.project.create.confirm" onClick={createProject}>Create project</Button></>}>{discard ? <p>Your unsaved project details will be lost.</p> : <div className="demo-form"><label>Project name<Input autoFocus maxLength={80} value={name} onChange={event => { setName(event.target.value); setFormError(''); }} placeholder="What are you working on?"/></label><label>Brief<Textarea maxLength={240} value={summary} onChange={event => setSummary(event.target.value)} placeholder="A sentence or two about the outcome."/></label>{formError ? <p role="alert">{formError}</p> : null}</div>}</Dialog>
    <Dialog open={!!selected} title={selected?.name} actionId="demo.project.details" onClose={() => setSelected(null)} footer={<Button actionId="demo.project.details.close" onClick={() => setSelected(null)}>Done</Button>}>{selected ? <div className="demo-details"><p className="demo-muted">{selected.summary}</p><div className="demo-details-meta"><span className="demo-avatar">{selected.initials}</span><span>{selected.owner}</span><span className="demo-status">{selected.state}</span></div><h2>Next milestones</h2>{selected.tasks.map(task => <p className="demo-milestone" key={task}><CheckCircle size={17}/>{task}</p>)}<div className="demo-details-bottom"><Clock size={15}/>Due {selected.due}</div></div> : null}</Dialog>
    <Dialog open={help !== null} title={help === 'about' ? 'Northstar' : 'Keyboard shortcuts'} actionId="demo.help.dialog" onClose={() => setHelp(null)} footer={<Button actionId="demo.help.close" onClick={() => setHelp(null)}>Done</Button>}>{help === 'about' ? <p>A fictional product workspace built with ChatGPT Desktop UI Kit. Edits reset on reload; your theme preference stays in this browser.</p> : <div className="demo-shortcuts"><p><span>Send a message</span><kbd>Enter</kbd></p><p><span>New line</span><kbd>Shift + Enter</kbd></p><p><span>Close a menu or dialog</span><kbd>Esc</kbd></p><p><span>Inspect a chart</span><kbd>← / →</kbd></p></div>}</Dialog>
    {notice ? <div className="demo-toast" role="status"><CheckCircle size={18}/>{notice}</div> : null}
  </div>;
}
createRoot(document.getElementById('root')!).render(<DesktopRoot storageKey="desktop-kit.demo.theme"><Demo/></DesktopRoot>);
